name: Update GitHub metrics

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: goolord
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          output_condition: data-changed
          plugins_errors_fatal: yes
