name: Refresh GitHub metrics

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: goolord
          filename: github-metrics.svg
